[core]
reloadable = true
order = 0

[package]
version = "0.0.2"
category = "Simulation"
title = "ROS UI (add-on)"
description = "Contains UI elements and scripts shared by the ROS add-on bridges"
authors = ["Toni-SM"]
repository = ""
keywords = ["add-on", "ROS"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[dependencies]
"omni.kit.uiapp" = {}
"omni.kit.commands" = {}
"omni.kit.menu.utils" = {}
"omni.usd" = {}
"omni.isaac.ros_bridge_ui" = {}
"omni.usd.schema.add_on" = {}

[[python.module]]
name = "omni.add_on.ros_bridge_ui"

[[python.module]]
name = "omni.add_on.ros_bridge_ui.tests"
public = false
