[core]
reloadable = true
order = 0

[package]
version = "0.0.3"
category = "Simulation"
feature = false
app = false
title = "ROS UI (add-on)"
description = "Contains UI elements and scripts shared by the ROS bridges (semu namespace)"
authors = ["Toni-SM"]
repository = "https://github.com/Toni-SM/semu.robotics.ros_bridge_ui"
keywords = ["command", "menu", "ROS"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[dependencies]
"omni.usd" = {}
"omni.kit.uiapp" = {}
"omni.kit.commands" = {}
"omni.kit.menu.utils" = {}
"omni.isaac.ros_bridge_ui" = {}
"semu.usd.schemas" = {}

[[python.module]]
name = "semu.robotics.ros_bridge_ui"

[[python.module]]
name = "semu.robotics.ros_bridge_ui.tests"
public = false
